rewards = [
    "Cup of Coffee",
    "15-Minute Nap Break",
    "Healthy Snack",
    "Relaxation Time",
    "Tech-Free Break",
    "Listen to Your Favorite Song",
    "Mindfulness Exercise",
    "Short Walk",
    "Reading Time",
    # "Social Media Break",
    "Stretching Session",
    "Creative Break",
    "Snack of Your Choice",
    "Water Break",
    "Mindful Breathing",
    "Quick Meditation",
    "Gaming Break",
    "Fresh Air Break",
    "Power Nap",
    "Chat with a Friend"
    "Outdoor Stroll",
    "Tea Time",
    "Healthy Smoothie",
    "Write in a Journal",
    "Desk Stretching",
    "Watch a Funny Video",
    "Organize Your Workspace",
    "Express Gratitude",
    "Learn a Fun Fact",
    # "Puzzle Time",
    # "DIY Project",
    "Breathing Exercises",
    "Visit a Plant",
    "Doodle Break",
    "Sunshine Break",
    "Positive Affirmations",
    # "Virtual Travel Experience",
    # "Coloring Break",
    "Laugh Break",
    "Inspiring Podcast",
    "Learn Something New",
    "Healthy Snack",
    "Express Creativity",
    "Play an Instrument",
    "Technology Timeout",
    "Positive Quotes",
    "Virtual Museum Tour",
    "Self-care Moment",
    # "Desk Yoga"
]